# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(verbose_name='Create Time')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(verbose_name='Create Time')),
            ],
        ),
        migrations.AddField(
            model_name='plugin',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betterboy.Site'),
        ),
    ]
