# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterboy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='WebSite',
        ),
    ]
