# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('betterboy', '0002_auto_20170109_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='website',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Time'),
        ),
    ]
